//! Test program to extract and verify generated Unity C# bindings
//!
//! This program demonstrates how to access the generate_unity_cs() methods
//! that are automatically generated by the GameComponent derive macro.
//!
//! For full bindings generation, use: ./scripts/generate_bindings.sh
//!
//! Run with: cargo run --package unity-network --example extract_bindings

use unity_network::{GameState, PacketHeader, PlayerPos, SpriteMessage};

fn main() {
    println!("=== Extracting Generated Unity C# Bindings ===\n");

    // Extract PacketHeader bindings
    println!("1. PacketHeader:");
    println!("{}", PacketHeader::generate_unity_cs());
    println!();

    // Extract PlayerPos bindings
    println!("2. PlayerPos:");
    println!("{}", PlayerPos::generate_unity_cs());
    println!();

    // Extract GameState bindings
    println!("3. GameState:");
    println!("{}", GameState::generate_unity_cs());
    println!();

    // Extract SpriteMessage bindings
    println!("4. SpriteMessage:");
    println!("{}", SpriteMessage::generate_unity_cs());
    println!();

    println!("=== Verification ===\n");

    // Verify that bindings contain expected content
    assert!(
        PacketHeader::generate_unity_cs().contains("public struct PacketHeader"),
        "PacketHeader binding missing struct definition"
    );
    assert!(
        PlayerPos::generate_unity_cs().contains("public struct PlayerPos"),
        "PlayerPos binding missing struct definition"
    );
    assert!(
        GameState::generate_unity_cs().contains("public unsafe struct GameState"),
        "GameState binding missing struct definition"
    );
    assert!(
        SpriteMessage::generate_unity_cs().contains("public unsafe struct SpriteMessage"),
        "SpriteMessage binding missing struct definition"
    );

    // Verify StructLayout attribute
    assert!(
        PacketHeader::generate_unity_cs().contains("[StructLayout"),
        "Missing StructLayout attribute"
    );
    assert!(
        PlayerPos::generate_unity_cs().contains("[StructLayout"),
        "Missing StructLayout attribute"
    );
    assert!(
        GameState::generate_unity_cs().contains("[StructLayout"),
        "Missing StructLayout attribute"
    );
    assert!(
        SpriteMessage::generate_unity_cs().contains("[StructLayout"),
        "Missing StructLayout attribute"
    );

    // Verify namespace
    assert!(
        PacketHeader::generate_unity_cs().contains("namespace GameFFI"),
        "Missing GameFFI namespace"
    );
    assert!(
        PlayerPos::generate_unity_cs().contains("namespace GameFFI"),
        "Missing GameFFI namespace"
    );
    assert!(
        GameState::generate_unity_cs().contains("namespace GameFFI"),
        "Missing GameFFI namespace"
    );
    assert!(
        SpriteMessage::generate_unity_cs().contains("namespace GameFFI"),
        "Missing GameFFI namespace"
    );

    println!("✓ All bindings verified successfully!");
    println!();
    println!("Next Steps:");
    println!("1. For full bindings generation, use: ./scripts/generate_bindings.sh");
    println!("2. Update Unity scripts to use GameFFI.PacketHeader, etc.");
    println!("3. Test Unity integration");
    println!();
    println!("To regenerate C# bindings automatically:");
    println!("  ./scripts/generate_bindings.sh");
}
