//! Generate complete Unity C# bindings file
//!
//! This program generates a complete GameFFI.cs file that can be
//! directly used in Unity. It combines all structs into a single file
//! with proper namespace and architecture warnings.
//!
//! Run with: ./scripts/generate_bindings.sh
//! Or manually: cargo run --package unity-network --example generate_unity_cs > unity/Generated/GameFFI.cs

use unity_network::{GameState, PacketHeader, PlayerPos, SpriteMessage};

fn main() {
    // File header
    println!("// GameFFI.cs");
    println!("//");
    println!("// Auto-generated by Rust's #[derive(GameComponent)] macro");
    println!("// DO NOT EDIT MANUALLY - Regenerate with:");
    println!("//   ./scripts/generate_bindings.sh");
    println!();

    // Architecture warning
    println!("// ⚠️⚠️⚠️ CRITICAL ARCHITECTURE WARNING ⚠️⚠️⚠️");
    println!("//");
    println!("// Unity is a VIEW LAYER ONLY. Unity must NEVER create packets manually.");
    println!("//");
    println!("// ✅ CORRECT USAGE:");
    println!("//   - Use PacketBuilder.CreateXxx() methods to let Rust FFI generate packets");
    println!("//   - Use GameFFI.FromBytes() to parse received packets from Rust");
    println!("//   - Use GameFFI.validate() to validate received packets");
    println!("//");
    println!("// ❌ FORBIDDEN USAGE:");
    println!("//   - DO NOT use GameFFI structs to create packets in Unity code");
    println!("//   - DO NOT manually set request_uuid fields in Unity");
    println!("//   - DO NOT call GameFFI.Create() (these methods are NOT generated)");
    println!("//");
    println!("// ALL packet creation (including request_uuid generation) happens in Rust FFI.");
    println!(
        "// Unity only provides business data (player_id, x, y, etc.) and Rust handles the rest."
    );
    println!();

    // Using statements
    println!("using System;");
    println!("using System.Runtime.InteropServices;");
    println!("using System.Text;");
    println!();

    // Namespace
    println!("namespace GameFFI");
    println!("{{");
    println!();

    // PacketType enum
    println!("    /// <summary>");
    println!("    /// Discriminator for packet types");
    println!("    /// Every packet MUST start with one of these");
    println!("    /// </summary>");
    println!("    public enum PacketType : byte");
    println!("    {{");
    println!("        KeepAlive = 0,");
    println!("        PlayerPos = 1,");
    println!("        GameState = 2,");
    println!("        SpriteMessage = 3,");
    println!("    }}");
    println!();

    // Helper enums for SpriteMessage
    println!("    /// <summary>");
    println!("    /// Sprite operation types");
    println!("    /// </summary>");
    println!("    public enum SpriteOp : byte");
    println!("    {{");
    println!("        Create = 0,");
    println!("        Update = 1,");
    println!("        Delete = 2,");
    println!("        Snapshot = 3,");
    println!("    }}");
    println!();

    println!("    /// <summary>");
    println!("    /// Sprite type enum (extensible for future types)");
    println!("    /// </summary>");
    println!("    public enum SpriteType : byte");
    println!("    {{");
    println!("        Serrif = 0,");
    println!("    }}");
    println!();

    // Extract and print struct definitions
    let header_code = PacketHeader::generate_unity_cs();
    let player_pos_code = PlayerPos::generate_unity_cs();
    let game_state_code = GameState::generate_unity_cs();
    let sprite_msg_code = SpriteMessage::generate_unity_cs();

    extract_struct_from_generated_code(header_code);
    extract_struct_from_generated_code(player_pos_code);
    extract_struct_from_generated_code(game_state_code);
    extract_struct_from_generated_code(sprite_msg_code);

    // FfiError enum
    println!("    /// <summary>");
    println!("    /// Error codes returned from FFI");
    println!("    /// </summary>");
    println!("    public enum FfiError : int");
    println!("    {{");
    println!("        Success = 0,");
    println!("        InvalidPointer = -1,");
    println!("        InvalidMagic = -2,");
    println!("        UnknownPacketType = -3,");
    println!("        BufferTooSmall = -4,");
    println!("        Disconnected = -5,");
    println!("        AlreadyConnected = -6,");
    println!("        InvalidUrl = -7,");
    println!("        CertValidationFailed = -8,");
    println!("        PanicCaught = -99,");
    println!("    }}");
    println!();

    // Close namespace
    println!("}}");
}

/// Extract struct definition from full generated C# code
/// The generated code includes namespace wrapper - we only need to struct itself
fn extract_struct_from_generated_code(full_code: String) {
    let lines: Vec<&str> = full_code.lines().collect();

    // State machine for parsing
    let mut phase = 0; // 0: find struct, 1: find opening brace, 2: track braces
    let mut brace_count = 0i32;

    for line in &lines {
        let trimmed = line.trim();

        // Phase 0: Skip header until we find struct definition
        if phase == 0 {
            if trimmed.contains("[StructLayout") || trimmed.contains("public struct") {
                phase = 1;
                // Print this line and subsequent lines
                println!("    {}", trimmed);
            }
            continue;
        }

        // Phase 1: Look for opening brace
        if phase == 1 {
            println!("    {}", trimmed);
            if trimmed.contains('{') {
                phase = 2;
                brace_count += trimmed.matches('{').count() as i32;
                brace_count -= trimmed.matches('}').count() as i32;
            }
            continue;
        }

        // Phase 2: Track braces to know when struct ends
        brace_count += trimmed.matches('{').count() as i32;
        brace_count -= trimmed.matches('}').count() as i32;

        // Print line with proper indentation
        if trimmed.is_empty() {
            println!();
        } else {
            println!("    {}", trimmed);
        }

        // Stop when all braces are closed (struct complete)
        if brace_count == 0 {
            println!();
            break;
        }
    }
}
